### ISSUE TITLE
Add node with guaranteed probability = 0

### ISSUE THREAD

**Issue by Wuzzy2** [octacian/advschem#2]
Add node with guaranteed probability = 0.
I suggest you add a node with an guaranteed probability of 0.

This should be an invisible (or at least barely visible),pointable, instantly minable, non-walkable, non-explodable node with a small selection box (maybe 1/5). If this node is saved into a schematic, the probability will always be 0, meaning that the schematic keeps the target node unchanged when placed.

If this node is placed into the schemtic tab, it gets rejected because the point of this node is to have a *forced* probability of 0.

I think such a feature is quite essential because I often want schematics to *not* overwrite exsiting nodes, not even with air. One use case is a room where you want the interiour to be filled with air, but leave the exteriour mostly alone.

Based on my thoughts here:

https://forum.minetest.net/viewtopic.php?f=47&t=15272&view=unread#p288670

**Comment by octacian** [comment]
Closing. See https://forum.minetest.net/viewtopic.php?f=11&t=18515&p=314273#p314273 (Wuzzy's version).
