### ISSUE TITLE
Border can be punched and destroyed

### ISSUE THREAD

**Issue by Wuzzy2** [octacian/advschem#4]
I noticed that the border has a selection box which can be pointed at and punched and even destroyed by punching and other forms of damage.

Possible solution:
* Zero-out the selection box to prevent pointing
* Add the entity to the armor group `immortal=1` after spawning

**Comment by octacian** [comment]
Immortal is already added to the entity as an armor group `on_activate` (https://github.com/octacian/advschem/blob/master/init.lua#L822). Aside from that, it is purposeful that someone with access to the schematic creator block can punch the border to hide it; essentially a shortcut to the GUI button.

**Comment by octacian** [comment]
Closing. See https://forum.minetest.net/viewtopic.php?f=11&t=18515&p=314273#p314273 (Wuzzy's version).
