### ISSUE TITLE
Saving nodes with probability=0 is broken and fails randomly

### ISSUE THREAD

**Issue by Wuzzy2** [octacian/advschem#5]
I have tried several times to save a schematic with nodes of probability = 0, but I often failed.

When I want to place the schematic again, it often happened that the nodes in question are actually placed with maximum probability (255).
It seems to happen more likely after I worked with many schematics in succession.
And just to be sure, I also restarted Minetest between every save and loading attempt.

What I did:
- Placed the thing I want so save
- Used a glass node and set probability 0 for it
- Placed said glass node everywhere where I do not want to overwrite nodes
- Select region, entered name and saved
- Restart Minetest and placed the schematic with `/placeschem`

If I was lucky, the glass nodes should now have disappered.
But if I was unlucky, the glass nodes are still there.

This bug breaks a key use case of this mod, sadly. :-(

**Comment by octacian** [comment]
Closing. See https://forum.minetest.net/viewtopic.php?f=11&t=18515&p=314273#p314273 (Wuzzy's version).
